name: "Test Features"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - cuda-12.6-ubuntu-24.04
          - cuda-12.4-ubuntu-22.04
          - cuda-11.8-ubuntu-20.04
          - cuda-11.4-ubuntu-18.04
          - cuda-with-cudnn
          - cuda-with-toolkit
          - debian-13
          - debian-12
          - debian-11
          - debian-10
    steps:
      - uses: actions/checkout@v4

      - name: "Install devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Test '${{ matrix.scenario }}' scenario"
        run: |
          devcontainer features test \
            --features nvidia-cuda \
            --skip-scenarios \
            --base-image "$(jq -r '."${{ matrix.scenario }}".image' test/nvidia-cuda/scenarios.json)" \
            --project-folder .

  test-scenarios:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: "Install devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Run scenario tests"
        run: devcontainer features test --features nvidia-cuda --project-folder .
